FROM <%= registry %>/baseimage-node8.9.0


RUN yum update -y &&\ 
  yum install -y  nasm libpng12 &&\
  yum clean all

COPY app/package.json app/package-lock.json /
RUN npm install

RUN pip install --upgrade pip &&\
  pip install dumb-init &&\
  pip install supervisor

<%= dockerfile_entrypoint_at_commit '7170f0f34e4d6cafada7adc5ba6b0f89ac35d39c' %>
<%= sources_for_dockerfile :app %>
<%= git_info_for_dockerfile %>

CMD ["ruby", "/entrypoint"]
WORKDIR /app
