source 'https://rubygems.org'
#gemspec
gem 'docker-api', '~> 1.29', '>= 1.29.2'
gem 'git', '~> 1.3'
gem 'terminal-table', '~> 1.7', '>= 1.7.3'
gem 'deep_merge', '~> 1.1', '>= 1.1.1'
gem 'colorize', '~> 0.8.1'
gem 'thor', '~> 0.19.4'
gem 'jwt', '~> 1.5', '>= 1.5.6'
gem 'parseconfig', '~> 1.0', '>= 1.0.8'

group :development do
  #gem "guard-rspec"
  #gem "pry"
end

group :test do  
  gem "rspec" 
end